"""removed model

Revision ID: 2efe0cbed1cb
Revises: f18033875dff
Create Date: 2025-03-05 02:10:46.227148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2efe0cbed1cb'
down_revision = 'f18033875dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responses',
    sa.Column('quizId', sa.VARCHAR(length=100), nullable=False),
    sa.Column('questionId', sa.VARCHAR(length=100), nullable=False),
    sa.Column('userId', sa.VARCHAR(length=100), nullable=False),
    sa.Column('userResponse', sa.VARCHAR(length=500), nullable=False),
    sa.Column('marksScored', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['questionId'], ['questions.questionId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quizId'], ['quizzes.quizId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quizId', 'questionId', 'userId')
    )
    # ### end Alembic commands ###
