"""new property added in response

Revision ID: 2fc5686cb5b0
Revises: ec10e886f2e3
Create Date: 2025-03-26 00:02:41.409470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc5686cb5b0'
down_revision = 'ec10e886f2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isQuestionVisited', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_column('isQuestionVisited')

    # ### end Alembic commands ###
