"""adding createOn to subject model

Revision ID: 32c9ea303506
Revises: 414a2aa3f055
Create Date: 2025-03-01 14:10:54.231768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c9ea303506'
down_revision = '414a2aa3f055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdOn', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('createdOn')

    # ### end Alembic commands ###
