"""added chapter createdon

Revision ID: 6b1a94fb9ccc
Revises: 2efe0cbed1cb
Create Date: 2025-03-11 22:57:28.320181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1a94fb9ccc'
down_revision = '2efe0cbed1cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdOn', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_column('createdOn')

    # ### end Alembic commands ###
