"""updated admin model

Revision ID: ce9e7c5a33b0
Revises: c260afb2d693
Create Date: 2025-02-28 01:28:15.172167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce9e7c5a33b0'
down_revision = 'c260afb2d693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adminId', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('userName', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['userName'])
        batch_op.drop_column('id')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('id', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('userName')
        batch_op.drop_column('adminId')

    # ### end Alembic commands ###
