"""added column in quiz

Revision ID: ec10e886f2e3
Revises: 6b1a94fb9ccc
Create Date: 2025-03-16 01:25:07.422835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec10e886f2e3'
down_revision = '6b1a94fb9ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quizName', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('quizName')

    # ### end Alembic commands ###
