"""updated response model

Revision ID: f18033875dff
Revises: e5620eabda6c
Create Date: 2025-03-05 02:09:36.340710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18033875dff'
down_revision = 'e5620eabda6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responseId', sa.String(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('questionId')
        batch_op.drop_column('userId')
        batch_op.drop_column('quizId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quizId', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('userId', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('questionId', sa.VARCHAR(length=100), nullable=False))
        batch_op.create_foreign_key(None, 'questions', ['questionId'], ['questionId'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'quizzes', ['quizId'], ['quizId'], ondelete='CASCADE')
        batch_op.drop_column('responseId')

    # ### end Alembic commands ###
